@polinsar/polin_wishart_em/reduceDynRange
@polinsar/polin_wishart_em/makeClassLogTables
@polinsar/polin_wishart_em/eStep
@polinsar/polin_wishart_em/mStep 
@polinsar/polin_wishart_em/lnGenHyp
@polinsar/polin_wishart_em/makeGenHypWisdom
@polinsar/polin_wishart_em/removeCoherAmpBias
@polinsar/polin_wishart_em/plotClassTables
@polinsar/polin_wishart_em/polin_wishart_em
@polinsar/polin_wishart_em/integrateHypGeom
@polinsar/polin_wishart_em/calcAngDiffDistrib
@polinsar/polin_wishart_em/approxAngDiffDistrib

